Fix and update translations.
AyatanaIndicators/ayatana-indicator-notifications pull request #29
Opened 2022-09-11 12:53 UTC by sunweaver

Esp. fix / clean-up .gschema file(s) and its translation.

2022-09-11 23:06 UTC, tari01 requested changes

2022-09-11 23:06 UTC, tari01 commented on data/CMakeLists.txt
>  set (SCHEMA_FILE "${CMAKE_CURRENT_BINARY_DIR}/${SCHEMA_NAME}")
We can also drop SCHEMA_FILE.

2022-09-13 07:03 UTC, sunweaver commented on data/CMakeLists.txt
>  set (SCHEMA_FILE "${CMAKE_CURRENT_BINARY_DIR}/${SCHEMA_NAME}")
Amended.

2022-09-13 14:32 UTC, tari01 approved these changes

2022-09-13 14:33 UTC, merged